import { INodeType, INodeTypeDescription, NodeConnectionType } from 'n8n-workflow';

export class CreateCustomer implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Conta Azul - Create Customer',
		name: 'createCustomer',
		icon: 'file:ContaAzul.svg',
		group: ['Conta Azul'],
		version: 1,
		subtitle: 'Cria cliente',
		description: 'Cria cliente na Conta Azul',
		defaults: {
			name: 'Create Customer',
		},
		// eslint-disable-next-line n8n-nodes-base/node-class-description-inputs-wrong-regular-node
		inputs: [NodeConnectionType.Main],
		// eslint-disable-next-line n8n-nodes-base/node-class-description-outputs-wrong
		outputs: [NodeConnectionType.Main],
		requestDefaults: {
			baseURL: 'https://api.contaazul.com/v1/customers',
			method: 'POST',
			headers: {
				Accept: 'application/json',
				'Content-Type': 'application/json',
				Authorization: '={{ "Bearer " + $parameter["accessToken"] }}',
			},
			body: {
				name: '={{ $parameter["name"] }}',
				company_name: '={{ $parameter["company_name"] }}',
				email: '={{ $parameter["email"] }}',
				business_phone: '={{ $parameter["business_phone"] }}',
				mobile_phone: '={{ $parameter["mobile_phone"] }}',
				person_type: '={{ $parameter["person_type"] }}',
				document: '={{ $parameter["document"] }}',
				identity_document: '={{ $parameter["identity_document"] }}',
				state_registration_number: '={{ $parameter["state_registration_number"] }}',
				state_registration_type: '={{ $parameter["state_registration_type"] }}',
				city_registration_number: '={{ $parameter["city_registration_number"] }}',
				date_of_birth: '={{ $parameter["date_of_birth"] }}',
				notes: '={{ $parameter["notes"] }}',
				contacts: '={{ JSON.parse($parameter["contacts"] || "[]") }}',
				address: {
					zip_code: '={{ $parameter["zip_code"] }}',
					street: '={{ $parameter["street"] }}',
					number: '={{ $parameter["number"] }}',
					complement: '={{ $parameter["complement"] }}',
					neighborhood: '={{ $parameter["neighborhood"] }}',
				},
			},
		},
		properties: [
			{
				displayName: 'Access Token',
				name: 'accessToken',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				required: true,
			},
			{
				displayName: 'Customer Name',
				name: 'name',
				type: 'string',
				default: '',
				required: true,
			},
			{
				displayName: 'Company Name',
				name: 'company_name',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
			},
			{
				displayName: 'Business Phone',
				name: 'business_phone',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Mobile Phone',
				name: 'mobile_phone',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Person Type',
				name: 'person_type',
				type: 'options',
				options: [
					{ name: 'Natural (Pessoa Física)', value: 'NATURAL' },
					{ name: 'Legal (Pessoa Jurídica)', value: 'LEGAL' },
				],
				default: 'NATURAL',
			},
			{
				displayName: 'Document (CPF/CNPJ)',
				name: 'document',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Identity Document (RG)',
				name: 'identity_document',
				type: 'string',
				default: '',
			},
			{
				displayName: 'State Registration Number',
				name: 'state_registration_number',
				type: 'string',
				default: '',
			},
			{
				displayName: 'State Registration Type',
				name: 'state_registration_type',
				type: 'options',
				options: [
					{ name: 'No Contributor', value: 'NO_CONTRIBUTOR' },
					{ name: 'Contributor', value: 'CONTRIBUTOR' },
					{ name: 'Immune Contributor', value: 'IMMUNE_CONTRIBUTOR' },
				],
				default: 'NO_CONTRIBUTOR',
			},
			{
				displayName: 'City Registration Number',
				name: 'city_registration_number',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Date of Birth',
				name: 'date_of_birth',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Notes',
				name: 'notes',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Contacts',
				name: 'contacts',
				type: 'json',
				default: '[]',
				placeholder: '[{"name": "John", "business_phone": "9999-9999", "email": "john@example.com", "job_title": "Manager"}]',
			},
			{
				displayName: 'ZIP Code',
				name: 'zip_code',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Street',
				name: 'street',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Number',
				name: 'number',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Complement',
				name: 'complement',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Neighborhood',
				name: 'neighborhood',
				type: 'string',
				default: '',
			},
		],
	};
}
